"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.notificationModel = exports.actionModel = exports.orderModel = exports.paymentModel = exports.configModel = exports.tokenModel = exports.messageModel = exports.signinModel = exports.turnoverModel = exports.carmiModel = exports.productModel = exports.userModel = void 0;
const tslib_1 = require("tslib");
const user_1 = tslib_1.__importDefault(require("./user"));
exports.userModel = user_1.default;
const product_1 = tslib_1.__importDefault(require("./product"));
exports.productModel = product_1.default;
const carmi_1 = tslib_1.__importDefault(require("./carmi"));
exports.carmiModel = carmi_1.default;
const turnover_1 = tslib_1.__importDefault(require("./turnover"));
exports.turnoverModel = turnover_1.default;
const signin_1 = tslib_1.__importDefault(require("./signin"));
exports.signinModel = signin_1.default;
const message_1 = tslib_1.__importDefault(require("./message"));
exports.messageModel = message_1.default;
const token_1 = tslib_1.__importDefault(require("./token"));
exports.tokenModel = token_1.default;
const config_1 = tslib_1.__importDefault(require("./config"));
exports.configModel = config_1.default;
const payment_1 = tslib_1.__importDefault(require("./payment"));
exports.paymentModel = payment_1.default;
const order_1 = tslib_1.__importDefault(require("./order"));
exports.orderModel = order_1.default;
const action_1 = tslib_1.__importDefault(require("./action"));
exports.actionModel = action_1.default;
const notification_1 = tslib_1.__importDefault(require("./notification"));
exports.notificationModel = notification_1.default;
//# sourceMappingURL=index.js.map